### ISSUE TITLE
Mouse input issue I noticed

### ISSUE THREAD

**Issue by CrusoeDaWolf** [YaLTeR/OpenAG#10]
I recently noticed that the input in Xash was different compared to the input in the original GoldSrc. Apparently, enabling v-sync seems to make the mouse input have a slight delay (or maybe it's just me).

When I tried OpenAG, the mouse input still felt the same until I disabled v-sync in original GoldSrc using the command:
gl_vsync 0

After that, mouse input felt much more precise. You might want to make a wiki or something with information like this.

**Comment by YaLTeR** [comment]
Pretty sure no one plays HL1 with VSync to avoid capping their FPS. Higher FPS in HL1 means, among other stuff, higher air acceleration. The "standard" FPS values for AG are 250 and 125.

**Comment by CrusoeDaWolf** [comment]
Alright, just stating that out xP

It's just that by default, it seems to be enabled and it bugged me that the mouse input was slower compared to Xash.
