### ISSUE TITLE
Can't jump in Xash3D SDL

### ISSUE THREAD

**Issue by CrusoeDaWolf** [YaLTeR/OpenAG#11]
The new update works great on GoldSrc (Good job! Really excited to see the new CTF stuff getting in now), but there is a slight problem; I can't jump in Xash. At all. I've tested it with Xash3D SDL v0.18 release. I've tried disabling auto jump, but it didn't do anything. I guess it's RIP for Xash support. 

I'm not entirely sure what the problem is. I'll post a log tomorrow. I suggest you get the newest Xash release and copy over your AG folder + OpenAG and take a look yourself. You might have a better idea of what's going on. I've tried rebinding jump as well with no luck.

**Comment by YaLTeR** [comment]
I looked into it. Xash3D doesn't seem to run the movement prediction from the client DLL (at least not in singleplayer mode, didn't test mp because the Create Server menu button is grayed out?) which results in autojump always assuming the player is flying in the air and so releasing the jump button. If you set `cl_autojump` to `0` then you can jump.

**Comment by CrusoeDaWolf** [comment]
Ah. If create server is blanked out, it might be the gameinfo.txt file

Find the line that says gamemode "singleplayer" and complety delete it

**Comment by YaLTeR** [comment]
Says `gamemode		"multiplayer_only"`

**Comment by CrusoeDaWolf** [comment]
Hm. How about the gameinfo.txt file in the valve directory?

**Comment by YaLTeR** [comment]
No gamemode line at all.

**Comment by CrusoeDaWolf** [comment]
Strange. It doesn't seem to be grayed out for me :/

Anyways, any idea when the next update will be coming out? :D

**Comment by YaLTeR** [comment]
Well I'm finishing up the CTF stuff today.

**Comment by CrusoeDaWolf** [comment]
Seems to be fixed now. Closing.
