### ISSUE TITLE
Independent physics

### ISSUE THREAD

**Issue by execut4ble** [YaLTeR/OpenAG#132]
Obviously this would be quite a big change, but something like [ezQuake's independent physics](http://www.ezquake.com/docs/guides/independent-physics.html) would allow players to have unlimited fps without changing the movement physics.

**Comment by YaLTeR** [comment]
Pretty sure this needs changes in the engine.

**Comment by YaLTeR** [comment]
Closing as it's not really actionable from OpenAG.

**Comment by sabianroberts** [comment]
I think the game DLL in the SDK can have a new physics system, for example [Half-Life ADM](https://github.com/Admer456/halflife-ADM) has the Bullet physics engine, and I *think* that the RPG projectiles use the new physics system. Though I'm not entirely sure

**Comment by YaLTeR** [comment]
This is not about adding a physics engine, this is about adding a tick system separate from render FPS like in Source.

**Comment by sabianroberts** [comment]
Ah, I see. Sorry about that.
