### ISSUE TITLE
Can u fix ' in nickname. When i wrote nick for example dexp'n'LG players see only dexp

### ISSUE THREAD

**Issue by naseonelove** [YaLTeR/OpenAG#134]

**Comment by YaLTeR** [comment]
Where do you write it?

**Comment by chinese-soup** [comment]
You have to quote your nickname in the console:
`name "dexp'n'LG"`
(Put in double quotes when trying to use `'` inside nickname)

or use the Options -> Multiplayer menu to set your nickname, without the quotation marks.
