### ISSUE TITLE
What about add old style customtimer & cl_old_scoreboard_position?

### ISSUE THREAD

**Issue by naseonelove** [YaLTeR/OpenAG#138]

**Comment by YaLTeR** [comment]
Why?

**Comment by naseonelove** [comment]
Why not)
You added jumpspeed, ye? It is useless for AG players) q

**Comment by YaLTeR** [comment]
Why, jumpspeed was an explicit request by a HLKZ player.

**Comment by YaLTeR** [comment]
Why not: it's a code that someone has to write, someone has to maintain, it's extra cvars that add clutter.

**Comment by naseonelove** [comment]
But in u'r client not only bhoppers and speedruners plays)

**Comment by YaLTeR** [comment]
Well, you still haven't said why non-bhoppers or speedrunners would need this.

**Comment by naseonelove** [comment]
Ok
1) is it difficult codes?
2) why players need ^10(black color) in chat?

**Comment by YaLTeR** [comment]
I suppose you don't have any justification, I'll close the issue then
