### ISSUE TITLE
Mac OSX package?

### ISSUE THREAD

**Issue by CrusoeDaWolf** [YaLTeR/OpenAG#15]
Would there be a possibility for a Mac OSX port or would you need access to a Mac yourself?

**Comment by YaLTeR** [comment]
Yeah, I don't have a Mac unfortunately.

**Comment by CrusoeDaWolf** [comment]
Alright. I'll ask my dad if I can use his Mac sometime to compile. Could you give me instructions to compile?

Also, what version of gcc should I use?

**Comment by YaLTeR** [comment]
That would be kinda complicated because there's some extra stuff I did for Windows and Linux and I've no idea what challenges you might find trying to do similar stuff on Mac.

**Comment by YaLTeR** [comment]
@Matherunner added macOS support in 655ffc9d0fc73b4faca8c750e798e4615474afa8! :tada: You can grab it from openag.pro. Testing would be appreciated.
