### ISSUE TITLE
cl_hide_center_messages

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/OpenAG#151]
Useful for removing an additional mode of HUD timer from KreedZ plugin in demos. 

Example screenshot with the issue: 

![20211210044157_1](https://user-images.githubusercontent.com/58108407/145497913-77508d9f-de32-4a4f-9801-a1f37c512d89.jpg)

A block of code that prints messages to the screen centered:
https://github.com/YaLTeR/OpenAG/blob/2c43e93c5445dc2543311fb88c2f0f287cde125d/cl_dll/text_message.cpp#L202-L205

**Comment by YaLTeR** [comment]
Maybe hide instead of ignore?
