### ISSUE TITLE
audio clicking in left ear, no matter if sound is playing or not (linux)

### ISSUE THREAD

**Issue by Glitch31415** [YaLTeR/OpenAG#197]
if volume is non-zero, there is an intermittent clicking sound in the left ear, about once every 3/4 of a second
separately, when the volume is set to a very high number (noticeable at >10) there's some static droning and tones, even when no sound is playing

this is a problem in base Half-Life, but i was wondering if you guys could fix it before valve does

**Comment by YaLTeR** [comment]
Mixing is on the engine side. I don't imagine OpenAG can do anything here.

**Comment by execut4ble** [comment]
Do you have a video of the problem? Just curious since I never noticed this issue.

Try increasing your `_snd_mixahead` value and see if it disappears? I believe it's at 0.1 by default.

**Comment by Glitch31415** [comment]
_snd_mixahead doesn't change it at all. my normal value is 0.05, but 0.1 and 1 both still have the issue

**Comment by Glitch31415** [comment]
![Screenshot from 2024-12-14 12-15-27](https://github.com/user-attachments/assets/342db96d-4260-4a21-a5b9-36cdec451101)
obs picks it up, i'm gonna upload my recording now

**Comment by Glitch31415** [comment]
this is what it sounds like in-game, turn your volume up to hear it better
https://youtu.be/MABiZWTzK7w
turn your volume down for this, the example of the droning (but it also has the clicking) in the main menu
https://youtu.be/AaRqGRuABaA
