### ISSUE TITLE
Left-handed weapon mode

### ISSUE THREAD

**Issue by execut4ble** [YaLTeR/OpenAG#25]
Add cl_lefthand 1 or cl_righthand 0 like in CS 1.6 to have weapons on the left side of the screen.

**Comment by YaLTeR** [comment]
Wait isn't this already possible through some setting?

**Comment by Traderain** [comment]
Some better command name would be appreciated tho :d

**Comment by execut4ble** [comment]
No, it's only possible in CS

**Comment by YaLTeR** [comment]
There's a part of this compiled into the engine, thankfully without any game dir checks, so I was able to add it.
