### ISSUE TITLE
CTF Score

### ISSUE THREAD

**Issue by senselessxo** [YaLTeR/OpenAG#32]
OpenAG shows total frags score (like if it was tdm) instead of total captures per team in CTF, so it is not possible to know which team is winning while playing this gamemode

Original AG client did show the captures as the team score, regardless of the frag count

**Comment by YaLTeR** [comment]
Should be fixed in https://github.com/YaLTeR/OpenAG/commit/cc1389ac8ee215bf5a5d6ece0c23c04a82a34927.
