### ISSUE TITLE
Add an option to display deathnotices separately from the HUD

### ISSUE THREAD

**Issue by execut4ble** [YaLTeR/OpenAG#35]
Just like cl_draw_only_deathnotices 1 in CSGO. Great for fragmovies when you want the deathnotices to be visible but the rest of the HUD turned off (hud_draw 0)

**Comment by YaLTeR** [comment]
Added in https://github.com/YaLTeR/OpenAG/commit/b7d482edff43cd386986a7994839a070b7d35bbc.
