### ISSUE TITLE
Fix death animation not fully playing out on clients that have high fps values

### ISSUE THREAD

**Issue by execut4ble** [YaLTeR/OpenAG#40]
Basically fix standing up dead corpses.

Might be doable clientside, not sure.

**Comment by YaLTeR** [comment]
Not 100% sure but I think this is the issue (serverside): https://github.com/YaLTeR/OpenAG/blob/master/dlls/player.cpp#L1295 But may be fixable clientside as well.

**Comment by YaLTeR** [comment]
Fixed in https://github.com/YaLTeR/OpenAG/pull/78.
