### ISSUE TITLE
Make the delay before respawning consistent on all fps values

### ISSUE THREAD

**Issue by execut4ble** [YaLTeR/OpenAG#41]
Currently players with the highest fps values will respawn the fastest, giving an advantage to higher fps players.

Perhaps base it on 100fps respawn speed.

**Comment by YaLTeR** [comment]
I'm not 100% sure but I think this is serverside, related to this: https://github.com/YaLTeR/OpenAG/blob/master/dlls/player.cpp#L1295 This is probably also the cause of the dead corpses bug.

**Comment by execut4ble** [comment]
Could probably be fixed if the client doesn't allow to respawn after a certain amount of time has passed, even if the server has no fix.

**Comment by YaLTeR** [comment]
I don't think that's a good idea because it'll introduce a disadvantage to OpenAG compared to AG, I think it would be better to make an AMXX or Metamod plugin for the server (or modify the AG DLL, obviously).

**Comment by execut4ble** [comment]
Fixed in AG 6.7, don't think this is relevant here anymore.
