### ISSUE TITLE
could not load library .../client.so

### ISSUE THREAD

**Issue by Toppatsu** [YaLTeR/OpenAG#42]
After run AG from Steam or directly with LD_LIBRARY_PATH and runtime libs from Steam, i see:

> could not load library /home/outbreak/.steam/steam/steamapps/common/Half-Life/./ag/cl_dlls/client.so

Half-life itself working good.
Debian Testing (multiarch), Steam from official repos.
Linux hikari 4.9.0-3-amd64 #1 SMP Debian 4.9.25-1 (2017-05-02) x86_64 GNU/Linux

**Comment by YaLTeR** [comment]
Hmm, could you try using runtime libs from your system instead of Steam's? Several distributions provide this option of running Steam already so you can probably do it on Debian.

**Comment by Toppatsu** [comment]
Could not find all necessary packages in Debian testing (libpng12-0). This is a real lack of using Testring...

**Comment by YaLTeR** [comment]
This is kinda complicated, but could you run HL with gdb, and break on `FS_LoadLibrary` (this symbol is inside `hw.so`) when it's loading `client.so`, then step through `dlopen()` and check the string returned by `dlerror()`? Not sure if there's an easier way to get the actual error reason for loading `client.so`.

**Comment by Toppatsu** [comment]
Did not work with gdb except developing in IDE, but I'll try.

**Comment by Toppatsu** [comment]
I's possible to manually call dlerror() after dlopen called in FS_LoadLibrary and print result? I cant' see what  FS_LoadLibrary call dlerror().

**Comment by YaLTeR** [comment]
Yes, you just do `x/s dlerror()` in gdb.

**Comment by Toppatsu** [comment]
dlerror: version `CURL_OPENSSL_4' not found (required by ./client.so)

**Comment by YaLTeR** [comment]
Interesting, I see. Looks like curl I'm using depends on `libcurl.so.4` which you don't have?

**Comment by Toppatsu** [comment]
I'am trying with `libcurl3` from debian testring repo and from steam - some result.

Debian testing:

> libcurl3:i386
> 
> /usr/lib/i386-linux-gnu/libcurl.so.3
> /usr/lib/i386-linux-gnu/libcurl.so.4
> /usr/lib/i386-linux-gnu/libcurl.so.4.4.0

Steam runtime:

> ./steam-runtime/i386/usr/lib/i386-linux-gnu/libcurl.so.4

**Comment by YaLTeR** [comment]
Sorry, I wrote the wrong thing. I meant it depends on a newer OpenSSL. I'm not very experienced with curl or OpenSSL, but it might be possible to make the OpenAG curl depend on an earlier OpenSSL version (as this seems to be the issue?).

**Comment by Toppatsu** [comment]
If even Debian Testring contain too earlier OpenSSL library -  i think really desirable to change it by more relevent version.

**Comment by YaLTeR** [comment]
Should be fixed in https://github.com/YaLTeR/OpenAG/commit/a501d2125eb961c0ed10b180fcf03d7548f441e2

**Comment by YaLTeR** [comment]
Just released the version with the fix, download from http://openag.pro.
