### ISSUE TITLE
CVar for chat and team sounds

### ISSUE THREAD

**Issue by krangm** [YaLTeR/OpenAG#43]
for now theres no chat / team sounds at all (at least in linux build)

would be good to have something like `s_chatsound` for chat beeps and `s_teamsound` for cmds like `play_team` and `play_close`

actually teamsounds are pretty important sometimes

**Comment by execut4ble** [comment]
For a generic chat sound there is hud_saytext_sound

**Comment by krangm** [comment]
so would be good to have it on the list
http://openag.pro/docs/

**Comment by YaLTeR** [comment]
It's a standard Half-Life CVar so it doesn't go in that list.

**Comment by execut4ble** [comment]
Thanks for the suggestion, added it anyway, since this command is exclusive to OpenAG.

**Comment by krangm** [comment]
@YaLTeR sorry cant find anything related at these lists
http://txdv.github.io/cstrike-cvarlist/
http://apg-clan.org/fastdl/ag/docs/documentation.htm

can you please point me to that standard HL CVar

or better just make sounds enabled _by default_ as they always were in regular AG

**Comment by krangm** [comment]
Figured out with chat sounds, thanks @execut4ble 

continue in separate issue #46
