### ISSUE TITLE
Colorized chatlog in console

### ISSUE THREAD

**Issue by krangm** [YaLTeR/OpenAG#44]
sometimes you are too late to read in-game chat
ofc its logged in console but its rly hard readable among other data

would be good to have it colorized, for example green
so it will be pretty easy to spot chat lines in console in a short period

**Comment by YaLTeR** [comment]
It's in the engine so unfortunately I can't do that without risking VAC.

**Comment by execut4ble** [comment]
As an alternative just use hud_saytext_time with a really high value, this way the messages will stay on screen for a longer period of time.

**Comment by krangm** [comment]
@execut4ble it will be a total mess when chat is going

@YaLTeR https://ptpimg.me/d211e5.png

**Comment by execut4ble** [comment]
Feel free to submit a Pull Request if you got it working yourself.

**Comment by krangm** [comment]
@execut4ble unfortunately im not that smart to make PRs
but you can look into code here
https://github.com/LevShisterov/BugfixedHL
it works as showed on screenshot for a pretty long time and nobody got VACed

**Comment by YaLTeR** [comment]
Once again, it's in the engine so unfortunately I can't do that without risking VAC. I know that BugfixedHL does it and I know how they did it and how to do it. I'm saying that you cannot do it and guarantee VAC safety. "it works as showed on screenshot for a pretty long time and nobody got VACed" doesn't mean Valve won't update VAC tomorrow to trigger on that particular patch.
