### ISSUE TITLE
Forcemodel options

### ISSUE THREAD

**Issue by krangm** [YaLTeR/OpenAG#45]
imo would be much better to have cvars like `cl_forceteammatesmodel` and `cl_forceenemymodels` so you will not to have to enter force param for every model/team every time and just put these 2 in cfg and always have fixed models of teammates and enemys nomatter which team you are playing for.

what you think ?

**Comment by YaLTeR** [comment]
Added in https://github.com/YaLTeR/OpenAG/commit/b49200dfc8ff605d5a51a3c74dfa7bd843dd658a.
