### ISSUE TITLE
Aligning bug in HUD displaying ammo if amount is < 10

### ISSUE THREAD

**Issue by krangm** [YaLTeR/OpenAG#54]
pictures talk for themselves
![1](https://user-images.githubusercontent.com/25441068/34508879-8bda73ba-f055-11e7-90aa-16097360fee1.png)
![2](https://user-images.githubusercontent.com/25441068/34508880-8e8251dc-f055-11e7-86e8-62768ea493c1.png)

**Comment by YaLTeR** [comment]
Seems to be an engine issue, but should be possible to fix by not using reverse HUD string drawing.
