### ISSUE TITLE
cl_forceteammatemodel doesnt work in spectate mode

### ISSUE THREAD

**Issue by krangm** [YaLTeR/OpenAG#55]
when using `cl_forceenemymodel` and `cl_forceteammatemodel` and viewing from spectate, all players in any team have models set in `cl_forceenemymodel`

**Comment by YaLTeR** [comment]
That's because when you're spectating you aren't in any team (you are in a separate "Spectators" team).

**Comment by krangm** [comment]
supposed so
but is it fixable?

**Comment by YaLTeR** [comment]
Which team would it use instead?

**Comment by krangm** [comment]
team named same as your player model

**Comment by krangm** [comment]
bump

@YaLTeR make it please

**Comment by YaLTeR** [comment]
I'll make it whenever I have time and feel like working on OpenAG next time. In the meantime you're welcome to make it yourself and pull request. :slightly_smiling_face:

**Comment by krangm** [comment]
@YaLTeR OpenAG update when it ?

**Comment by chinese-soup** [comment]
Implemented by #106
