### ISSUE TITLE
Consider adding the clientside autojump.

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/OpenAG#6]
Everyone is using autojump scripts anyway, would be more precise and less hassle with _special to have a built-in autojump. Need to ask the community for opinions on this one though.

**Comment by Toppatsu** [comment]
This is a realy good idea. Oh, but _special nor working on actual stream. Please help me, how to enable bhop with current build of openAG?

**Comment by YaLTeR** [comment]
You can use the 6027 build of the engine.

**Comment by Toppatsu** [comment]
After reading [this](http://hldm.org/interes/stati/291-vozvraschenie-raspryga-v-half-life.html) topic  I'am rebuild client.dll with replacement "special" and "special" by my keywords, end its realy working.

**Comment by CrusoeDaWolf** [comment]
I think this would be a great idea. :D
A bit off topic, I noticed you modified pm_shared/pm_shared.c to remove the bhop cap
Are you planning on rebuilding the server binary as well?

**Comment by YaLTeR** [comment]
Nope, I did it because it's also used in the client (for prediction).

**Comment by CrusoeDaWolf** [comment]
Alright. Any idea when the next update will come out?

**Comment by YaLTeR** [comment]
Working on autojump in its branch. Will also probably add auto ducktap.

**Comment by YaLTeR** [comment]
Could also add a _special-like thing to execute commands every frame, not sure about that though.

**Comment by CrusoeDaWolf** [comment]
Awesome! :D 

As for a _special thing, maybe. I think we should focus on auto jump right now and bug fixing.

I tested this with Xash3D. It works with the SDL version from https://github.com/FWGS/xash3d but not the build from moddb, so I guess you could say it's somewhat compatible. :+1:

**Comment by YaLTeR** [comment]
After some thinking, I won't add autoducktap (gives too much of advantage over a simple duckspam script), but I'll add a _special replacement.

Weird that it doesn't work with the moddb Xash3D build, could you elaborate on what happens?

**Comment by CrusoeDaWolf** [comment]
It says it can't initialize client.dll

I'm guessing this has something to do with SDL2, as I also tried this with NGHL (Don't worry, I own HL. You can check my Steam xP) and it wouldn't launch AG, saying it couldn't find SDL2.dll

**Comment by CrusoeDaWolf** [comment]
`=================================================================================
	Xash3D 0.98 (build 3366) change game to 'Adrenaline Gamer Steam' at Aug10 2016 [10:49.17]
=================================================================================
=================================================================================
	Xash3D 0.98 (build 3366) started at Aug10 2016 [10:49.17]
=================================================================================
Sys_LoadLibrary: Loading xash.dll - ok
FS_Init: done
FS_LoadGameInfo( ag )
FS_Rescan( Adrenaline Gamer Steam )
Adding packfile: valve/pak0.pak (3453 files)
Adding wadfile valve/cached.wad (2 files)
Adding wadfile valve/decals.wad (222 files)
Adding wadfile valve/fonts.wad (3 files)
Adding wadfile valve/gfx.wad (7 files)
Adding wadfile valve/halflife.wad (3116 files)
Adding wadfile valve/liquids.wad (32 files)
Adding wadfile valve/spraypaint.wad (14 files)
Adding wadfile valve/xeno.wad (264 files)
Adding wadfile ag/aw_agctf.wad (42 files)
Adding wadfile ag/cached.wad (2 files)
Adding wadfile ag/gfx.wad (7 files)
Adding wadfile ag/liquids.wad (32 files)
Adding wadfile ag/spraypaint.wad (14 files)
InitDecals: 222 decals
Sys_LoadLibrary: Loading wsock32.dll - ok
NET_Init()
Console initialized.
execing video.cfg
execing opengl.cfg
Sys_LoadLibrary: Loading opengl32.dll - ok
GL_CheckExtension: OpenGL Internal ProcAddress - enabled
Set: Mode 20: 16x9 [1920x1080]
VID_ChoosePFD( color 24, alpha 8, depth 32, stencil 8 )
VID_ChoosePFD: using hardware acceleration
GL PFD: color( 32-bits ) alpha( 8-bits ) Z( 24-bit )
VID_StartupGamma: validate screen gamma - ok
GL_CheckExtension: OpenGL 1.1.0 - enabled
Video: GeForce GTX 960/PCIe/SSE2
GL_CheckExtension: WGL_EXT_swap_control - enabled
GL_CheckExtension: glDrawRangeElements - enabled
GL_CheckExtension: GL_ARB_multitexture - enabled
GL_CheckExtension: GL_ARB_texture_env_combine - enabled
GL_CheckExtension: GL_ARB_texture_env_dot3 - enabled
GL_CheckExtension: GL_EXT_texture3D - enabled
GL_CheckExtension: GL_SGIS_generate_mipmap - enabled
GL_CheckExtension: GL_ARB_texture_cube_map - enabled
GL_CheckExtension: GL_ARB_seamless_cube_map - enabled
GL_CheckExtension: GL_EXT_point_parameters - enabled
GL_CheckExtension: GL_ARB_texture_non_power_of_two - enabled
GL_CheckExtension: GL_ARB_texture_compression - enabled
GL_CheckExtension: GL_EXT_compiled_vertex_array - enabled
GL_CheckExtension: GL_EXT_texture_edge_clamp - enabled
GL_CheckExtension: GL_EXT_texture_filter_anisotropic - enabled
GL_CheckExtension: GL_EXT_texture_lod_bias - enabled
GL_CheckExtension: GL_ARB_texture_border_clamp - enabled
GL_CheckExtension: GL_EXT_blend_minmax - enabled
GL_CheckExtension: GL_EXT_blend_subtract - enabled
GL_CheckExtension: glStencilOpSeparate - enabled
GL_CheckExtension: GL_EXT_stencil_two_side - enabled
GL_CheckExtension: GL_ARB_vertex_buffer_object - enabled
GL_CheckExtension: GL_ARB_texture_env_add - enabled
GL_CheckExtension: GL_ARB_shader_objects - enabled
GL_CheckExtension: GL_ARB_shading_language_100 - enabled
GL_CheckExtension: GL_ARB_vertex_shader - enabled
GL_CheckExtension: GL_ARB_fragment_shader - enabled
GL_CheckExtension: GL_ARB_depth_texture - enabled
GL_CheckExtension: GL_ARB_shadow - enabled
GL_CheckExtension: GL_ARB_texture_float - enabled
GL_CheckExtension: GL_ARB_depth_buffer_float - enabled
GL_CheckExtension: GL_ARB_occlusion_query - enabled
GL_Upload: *white s&3 [1 x 1]
GL_Upload: *gray s&3 [1 x 1]
GL_Upload: *black s&3 [1 x 1]
GL_Upload: *vsdct s&3 [1 x 1]
SCR_Init()
Sys_LoadLibrary: Loading ../menu.dll - ok
Sys_LoadLibrary: Loading avifil32.dll - ok
Sys_LoadLibrary: Loading msvfw32.dll - ok
Sys_LoadLibrary: Loading msacm32.dll - ok
AVI_Initailize: done
GL_Upload: gfx/shell/min_n s&3 [19 x 19]
GL_Upload: gfx/shell/min_f s&3 [19 x 19]
GL_Upload: gfx/shell/min_d s&3 [19 x 19]
GL_Upload: gfx/shell/cls_n s&3 [19 x 19]
GL_Upload: gfx/shell/cls_f s&3 [19 x 19]
GL_Upload: gfx/shell/cls_d s&3 [19 x 19]
Sys_LoadLibrary: Loading dlls/ag.dll - ok
Sys_FreeLibrary: Unloading dlls/ag.dll
Sys_LoadLibrary: Loading dsound.dll - ok
SNDDMA_InitDirect: creating DS object - ok
DS_CreateBuffers: initialize
DS_CreateBuffers: setting EXCLUSIVE coop level - ok
DS_CreateBuffers: creating primary buffer - ok
DS_CreateBuffers: setting primary sound format - ok
DS_CreateBuffers: creating secondary buffer - ok
DS_CreateBuffers: using secondary sound buffer
Audio: DirectSound
Sys_LoadLibrary: Loading cl_dlls/client.dll - failed
DS_DestroyBuffers: shutdown
DS_DestroyBuffers: setting NORMAL coop level
DS_DestroyBuffers: stopping and releasing sound buffer
DS_DestroyBuffers: releasing primary buffer
Host_InitError: can't initialize client.dll
Sys_FreeLibrary: Unloading wsock32.dll
Sys_FreeLibrary: Unloading xash.dll

=================================================================================
	Xash3D 0.98 (build 3366)  at Aug10 2016 [10:49.22]
=================================================================================
`

**Comment by YaLTeR** [comment]
Ah yeah this thing. Forgot about it. Not sure what it is about.

**Comment by CrusoeDaWolf** [comment]
Anyways, doesn't bother me that much either way. I use the SDL version a lot more anyways xP
I just wanted to add my input on how well it works with Xash.

**Comment by YaLTeR** [comment]
Autojump: https://github.com/YaLTeR/OpenAG/commit/74551aec2a371a152a386d04e0c54f02cb05c657
