### ISSUE TITLE
Mouse acceleration

### ISSUE THREAD

**Issue by gustavomassa** [YaLTeR/OpenAG#69]
Hello Yalter,

First of all, thank you for the project, awesome!

I'm an old player (Fatal), from Brazil, I'm a Computer Engineer working as a software engineer(web, backend, microservices...). I don't have much experience in game development, but since I really love this game, I would like to somehow help it.

I would like to start by implementing the mouse accel feature. Do you have any technical doc, diagram, architecture diagram explaining how the project is structured? What IDE and SO are you using for development? Could you give me some overview so I could start?

**Comment by execut4ble** [comment]
If you want to use mouse acceleration, just toggle **m_rawinput 0**

**Comment by gustavomassa** [comment]
@execut4ble I mean mouse acceleration settings in-game, like other fps games have (quake, diabotical) for example.
Something like: cl_mouseaccel 0.1

**Comment by execut4ble** [comment]
Have you tried **m_customaccel** commands and if they provide sufficient settings for you?

**Comment by gustavomassa** [comment]
I did not know about m_customaccel, just tested it, works fine.
using rawinput 1 with customaccel works very well, but using rawinput 0 with customaccess 1 feels strange, too much acceleration.

```
sensitivity				"1.2"
zoom_sensitivity_ratio 	        "1.0"
m_filter 				        "1"
m_forward 				"1"
m_pitch 				       "0.022000"
m_side 				       "0.8"
m_yaw 				       "0.022"
m_rawinput  			       "1"
m_customaccel		       "1"
m_customaccel_exponent      "1"
m_customaccel_scale 	       "0.01"
m_customaccel_max 	       "0"	
ex_interp				       "0.05"
```

**Comment by YaLTeR** [comment]
So, is this issue solved, then?

If you're interested in contributing, check the README, it contains beginner-friendly set-up for Visual Studio on Windows and for GNOME Builder on Linux (although on Linux I'd recommend using your own favorite development environment since Builder isn't quite there with its IDE experience). I'm not sure what "SO" is. As for the structure, you're mainly interested in the contents of the cl_dll folder. Feel free to explore it on your own.

**Comment by YaLTeR** [comment]
Could you describe exactly what the issue is and how to reproduce it? It's not really actionable currently as I don't understand what's wrong and how to tell if it's wrong.
