### ISSUE TITLE
Mod_NumForName: models/player/[player]/[playermodelhere].mdl not found

### ISSUE THREAD

**Issue by vladimirbuzko** [YaLTeR/OpenAG#79]
Hi, when I go to the server, it crashes me with this error. What could be the problem?

![hl_Pa81ykgIN7](https://user-images.githubusercontent.com/50547371/84272549-3bea0e80-ab36-11ea-9e61-0391b614baf8.png)
![hl_DS18wDv57S](https://user-images.githubusercontent.com/50547371/84272600-502e0b80-ab36-11ea-96b9-34b456109a07.png)
![hl_5rYUijgyox](https://user-images.githubusercontent.com/50547371/84272615-54f2bf80-ab36-11ea-877f-83ae61441d00.png)
![hl_vd3esN2S5j](https://user-images.githubusercontent.com/50547371/84272627-58864680-ab36-11ea-9739-31f28f78f49f.png)

**Comment by pr0lert** [comment]
how to fix it?

**Comment by YaLTeR** [comment]
Idk, ask in the discord server
