### ISSUE TITLE
missing server gamedll in CMakeLists [ag.so, ag.dylib, ag.dll]

### ISSUE THREAD

**Issue by p5-vbnekit** [YaLTeR/OpenAG#80]
Hello! How to build gamedll? It seems like Makefile in the "dlls" folder is not relevant.
Or gamedll build scripts is only private? Thanks!

**Comment by YaLTeR** [comment]
Yes. The source code for them was published at https://github.com/martinwebrant/agmod, but I can't say anything on whether it builds or produces a working DLL, since it's a port of the AG code onto a newer HLSDK.
