### ISSUE TITLE
Playing demos twice crashes the game

### ISSUE THREAD

**Issue by mxpph** [YaLTeR/OpenAG#81]
I have recorded many demos on HL KreedZ and this issue happens with many of them. 
Steps for reproducing: 
1. Play a demo with `playdemo` 
2. Watch the demo
3. When disconnected, repeat the `playdemo` command
4. The game crashes

If needed I can attach some demos which this happens on. It doesn't happen on every demo, and it doesn't always crash (but it is often enough for me to notice a pattern).

**Comment by YaLTeR** [comment]
Fixed by 3b10cbb02809ca5f77e37c4ecf8cf9aa404520df.
