### ISSUE TITLE
hud_color rainbow

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/OpenAG#90]
A cvar to make hud rainbow.

**Comment by LeonN1** [comment]
Having something like this would be amazing
![IMG-20210115-WA0027](https://user-images.githubusercontent.com/77511070/104775191-f46bd680-5745-11eb-92d9-e3f6a1f07ae0.jpeg)

**Comment by SmileyAG** [comment]
Sorry for too late response, i'll closing this issue, since tmp64 implemented this feature already, big thanks to him!
